name: Dependency Review

on:
  pull_request:
    branches: ["main"]

jobs:
  dependency-review:
    if: ${{ !github.event.repository.private }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
